version: "3.8"

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql8.0.39
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_crm_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - main_app

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8.4
    restart: unless-stopped
    volumes:
      - ./root:/var/www/html
    depends_on:
      - mysql
    networks:
      - main_app

  nginx:
    image: nginx:stable-perl
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./root:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - main_app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - main_app

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - main_app

volumes:
  mysql_data:

networks:
  main_app:
